const fs=require('fs'),path=require('path');const root=path.resolve(__dirname,'..'),front=path.join(root,'frontend');const esbuild=require(front+'/node_modules/esbuild'),ts=require(front+'/node_modules/typescript'),sass=require(front+'/node_modules/sass');
const chain=path.basename(root).split('-')[0],out=process.argv[2]||path.join(__dirname,'dist');fs.mkdirSync(out,{recursive:true});

const provenance=[{path:'hub/feed.js',sha256:require('crypto').createHash('sha256').update(fs.readFileSync(path.join(__dirname,'feed.js'))).digest('hex')}];
esbuild.build({entryPoints:[path.join(__dirname,'entry.ts')],outfile:path.join(out,'strip.js'),bundle:true,format:'esm',minify:true,target:'es2022',nodePaths:[front+'/node_modules'],define:{ngDevMode:'false'},plugins:[{name:'native-source',setup(build){
 build.onResolve({filter:/^native-status-template$/},()=>({path:'native-status-template',namespace:'native-status'}));
 build.onLoad({filter:/.*/,namespace:'native-status'},()=>{
  const htmlPath='frontend/src/app/components/master-page/master-page.component.html',scssPath='frontend/src/app/components/master-page/master-page.component.scss';
  const html=fs.readFileSync(path.join(root,htmlPath),'utf8'),scss=fs.readFileSync(path.join(root,scssPath),'utf8');
  const badges=[0,1].map(state=>html.match(new RegExp('<div class="badge bg-warning"[^>]*connectionState\\.val === '+state+'[^>]*>[\\s\\S]*?<\\/div>'))?.[0]);
  const badgeStyle=scss.match(/\.badge\s*\{[^}]*\}/)?.[0];if(badges.some(x=>!x)||!badgeStyle)throw new Error('Native connection badge fragment changed; review extraction');
  for(const file of [htmlPath,scssPath])provenance.push({path:file,sha256:require('crypto').createHash('sha256').update(fs.readFileSync(path.join(root,file))).digest('hex')});
  return {contents:'export const nativeConnectionTemplate='+JSON.stringify('<ng-container *ngIf="{ val: state.connectionState$ | async } as connectionState">'+badges.join('\n')+'</ng-container>')+';export const nativeConnectionStyles='+JSON.stringify(sass.compileString(badgeStyle).css)+';',loader:'js'};
 });
 build.onResolve({filter:/^@app\//},args=>{const name=args.path.slice(5);if(/services\/(state|cache|storage|theme|eta)\.service$/.test(name))return {path:path.join(__dirname,'facade.ts')};return {path:path.join(front,'src/app',name+'.ts')};});
 build.onLoad({filter:/\.ts$/},args=>{let source=fs.readFileSync(args.path,'utf8'); if(!args.path.includes('/node_modules/'))provenance.push({path:path.relative(root,args.path),sha256:require('crypto').createHash('sha256').update(source).digest('hex')});
 source=source.replace(/templateUrl:\s*['"]([^'"]+)['"]/g,(_,file)=>'template:'+JSON.stringify(fs.readFileSync(path.resolve(path.dirname(args.path),file),'utf8'))).replace(/styleUrls:\s*\[([^\]]+)\]/g,(_,files)=>'styles:['+[...files.matchAll(/['"]([^'"]+)['"]/g)].map(m=>JSON.stringify(sass.compile(path.resolve(path.dirname(args.path),m[1]),{silenceDeprecations:['legacy-js-api','import','global-builtin','color-functions']}).css)).join(',')+']');
 const ast=ts.createSourceFile(args.path,source,ts.ScriptTarget.Latest,true);let append='';for(const node of ast.statements){if(ts.isClassDeclaration(node)&&node.name){const ctor=node.members.find(ts.isConstructorDeclaration);if(ctor){append+='\n'+node.name.text+'.ctorParameters=()=>['+ctor.parameters.map(p=>{const type=p.type?.getText(ast)||'undefined';const inject=(p.modifiers||[]).find(m=>ts.isDecorator(m)&&m.expression.getText(ast).startsWith('Inject('));return '{type:'+(/^[\w.]+$/.test(type)&&!['string','number','any','boolean'].includes(type)?type:'undefined')+(inject?',decorators:[{type:Inject,args:['+inject.expression.arguments[0].getText(ast)+']}]':'')+'}';}).join(',')+'];';}}}
 return {contents:ts.transpileModule(source+append,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext,experimentalDecorators:true,useDefineForClassFields:false}}).outputText,loader:'js'};
 });
}}]}).then(()=>{let css=sass.compile(path.join(front,'src/styles.scss'),{loadPaths:[front+'/node_modules'],silenceDeprecations:['import','global-builtin','color-functions','legacy-js-api'],logger:{warn(){},debug(){}}}).css;css=css.replace(/:root\b/g,':host').replace(/(?<![-\w])body(?![-\w])/g,'.native-scope');css+=fs.readFileSync(front+'/node_modules/@fortawesome/fontawesome-svg-core/styles.css','utf8');css+='\n:host{display:block;position:relative;overflow:hidden} .native-overlays{color:var(--fg);font-family:var(--bs-body-font-family)} .native-scope{display:block;position:relative;font-family:var(--bs-body-font-family);font-size:var(--bs-body-font-size);line-height:var(--bs-body-line-height);color:var(--fg);background:var(--active-bg);padding:0;height:260px}';fs.writeFileSync(out+'/strip.css',css);for(const item of [...provenance]){if(item.path.endsWith('.component.ts')){for(const ext of ['html','scss']){const file=item.path.replace(/ts$/,ext);if(fs.existsSync(path.join(root,file)))provenance.push({path:file,sha256:require('crypto').createHash('sha256').update(fs.readFileSync(path.join(root,file))).digest('hex')});}}}provenance.push({path:'frontend/src/styles.scss',sha256:require('crypto').createHash('sha256').update(fs.readFileSync(front+'/src/styles.scss')).digest('hex')});fs.writeFileSync(out+'/provenance.json',JSON.stringify({chain,sourceCommit:require('child_process').execFileSync('git',['rev-parse','HEAD'],{cwd:root,encoding:'utf8'}).trim(),files:provenance},null,2));fs.copyFileSync(path.join(front,'src/resources/mining-pools/default.svg'),path.join(out,'default.svg'));fs.copyFileSync(path.join(__dirname,'feed.js'),path.join(out,'feed.js'));console.log(out);}).catch(e=>{console.error(e);process.exit(1)});
